'use client';

import { useState, useEffect } from 'react';
import { userApi, calendarApi, type UserProfile } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { cn } from '@/lib/utils';
import { User, Inbox as InboxIcon, Bell, Calendar as CalendarIcon, Zap, CheckCircle2, Copy, Monitor, Sun, Moon } from 'lucide-react';
import { useTheme } from 'next-themes';
function errorMessage(error: unknown, fallback: string) { return error instanceof Error ? error.message : fallback; }
export default function SettingsPage() {
  const { user } = useAuth(); const [profile,setProfile]=useState<UserProfile|null>(null); const [forwardingAddress,setForwardingAddress]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [displayName,setDisplayName]=useState(''); const [timezone,setTimezone]=useState('UTC'); const [emailNotifications,setEmailNotifications]=useState(true); const [message,setMessage]=useState(''); const [copied,setCopied]=useState(false); const {theme,setTheme}=useTheme();
  useEffect(()=>{if(!user)return; Promise.all([userApi.getProfile(),userApi.getForwardingAddress()]).then(([p,f])=>{setProfile(p);setDisplayName(p.displayName||'');setTimezone(p.timezone);setEmailNotifications(p.notificationPrefs?.channels?.includes('email')??true);setForwardingAddress(f.address);}).catch(e=>setMessage(errorMessage(e,'Failed to load settings'))).finally(()=>setLoading(false));},[user]);
  const handleSave=async()=>{setSaving(true);setMessage('');try{const updated=await userApi.updateProfile({displayName:displayName||undefined,timezone,notificationPrefs:{channels:emailNotifications?['email']:[],default_offsets:profile?.notificationPrefs?.default_offsets||['7d','1d','2h']}});setProfile(updated);setMessage('Settings saved successfully.');setTimeout(()=>setMessage(''),3000);}catch(e){setMessage(errorMessage(e,'Failed to save settings'));}finally{setSaving(false);}};
  const handleDisconnectCalendar=async()=>{if(!window.confirm('Disconnect Google Calendar? Synced events will remain.'))return;try{await calendarApi.disconnect();setMessage('Google Calendar disconnected.');}catch(e){setMessage(errorMessage(e,'Failed to disconnect calendar'));}};
  const handleCopyForwarding=()=>{if(!forwardingAddress)return;navigator.clipboard.writeText(forwardingAddress).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000);});};
  if(loading)return <div className="max-w-2xl mx-auto space-y-6 animate-pulse"><div className="h-10 w-40 clay-surface rounded-2xl"/><div className="h-[250px] clay-surface rounded-[28px]"/><div className="h-[150px] clay-surface rounded-[28px]"/></div>;
  const inputClasses='w-full px-4 py-3 bg-surface-inset border border-border-strong rounded-2xl text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-brand/20 focus:border-brand transition-all shadow-neu-inset'; const labelClasses='block text-sm font-semibold text-text-secondary mb-2 ml-1'; const sectionClasses='clay-surface rounded-[28px] p-6 sm:p-8 transition-all';
  return <div className="max-w-2xl mx-auto pb-12"><div className="flex items-center gap-3 mb-8"><div className="w-11 h-11 rounded-2xl clay-inset text-brand flex items-center justify-center"><User className="w-5 h-5"/></div><div><h1 className="text-2xl font-bold text-text-primary tracking-tight">Settings</h1><p className="text-sm text-text-secondary">Manage your account and preferences</p></div></div>
    {message&&<div className={cn('mb-6 p-4 rounded-2xl text-sm font-semibold border shadow-neu flex items-center gap-2',message.includes('saved')||message.includes('disconnected')?'pastel-mint text-success':'pastel-peach text-warning')} role="status"><CheckCircle2 className="w-4 h-4"/>{message}</div>}
    <div className="space-y-6">
      <section className={sectionClasses}><div className="flex items-center gap-2 mb-6"><User className="w-5 h-5 text-brand"/><h2 className="text-lg font-bold text-text-primary">Profile</h2></div><div className="space-y-5"><div><label className={labelClasses} htmlFor="email">Email</label><input id="email" type="email" value={profile?.email||''} disabled className={cn(inputClasses,'opacity-70 cursor-not-allowed')}/></div><div><label className={labelClasses} htmlFor="display-name">Display Name</label><input id="display-name" type="text" maxLength={100} value={displayName} onChange={e=>setDisplayName(e.target.value)} className={inputClasses} placeholder="Your name"/></div><div><label className={labelClasses} htmlFor="timezone">Timezone</label><input id="timezone" type="text" value={timezone} onChange={e=>setTimezone(e.target.value)} className={inputClasses} placeholder="e.g., Asia/Kolkata"/></div></div></section>
      <section className={sectionClasses}><div className="flex items-center gap-2 mb-5"><Monitor className="w-5 h-5 text-brand"/><h2 className="text-lg font-bold text-text-primary">Appearance</h2></div><div className="grid grid-cols-3 gap-3">{[{id:'light',label:'Light',icon:Sun},{id:'dark',label:'Dark',icon:Moon},{id:'system',label:'System',icon:Monitor}].map(t=>{const active=theme===t.id;return <button key={t.id} onClick={()=>setTheme(t.id)} className={cn('flex flex-col items-center justify-center gap-2 min-h-[80px] rounded-2xl border transition-all clay-button',active?'bg-clay-lavender border-brand text-brand shadow-neu-inset':'bg-surface text-text-secondary border-border-subtle hover:bg-surface-hover hover:text-text-primary')}><t.icon className="w-5 h-5"/><span className="text-sm font-semibold">{t.label}</span></button>})}</div></section>
      <section className={sectionClasses}><div className="flex items-center gap-2 mb-5"><InboxIcon className="w-5 h-5 text-brand"/><h2 className="text-lg font-bold text-text-primary">Inbox Forwarding</h2></div><p className="text-sm text-text-secondary mb-5">Forward an email to this address to automatically extract deadlines.</p><div className="flex flex-col sm:flex-row gap-3"><input type="email" readOnly value={forwardingAddress} aria-label="Your DeadlineKeeper forwarding address" className={cn(inputClasses,'flex-1 min-w-0')}/><button type="button" onClick={handleCopyForwarding} className="clay-button flex items-center justify-center gap-2 px-5 min-h-[44px] rounded-2xl text-text-primary font-semibold">{copied?<CheckCircle2 className="w-4 h-4 text-success"/>:<Copy className="w-4 h-4 text-text-muted"/>}{copied?'Copied':'Copy'}</button></div></section>
      <section className={sectionClasses}><div className="flex items-center gap-2 mb-5"><Bell className="w-5 h-5 text-brand"/><h2 className="text-lg font-bold text-text-primary">Notifications</h2></div><label className="flex items-center gap-4 cursor-pointer p-4 rounded-2xl clay-inset"><input type="checkbox" checked={emailNotifications} onChange={e=>setEmailNotifications(e.target.checked)} className="w-5 h-5 text-brand rounded border-border-strong focus:ring-brand/20 bg-surface"/><div><span className="block text-sm font-semibold text-text-primary mb-0.5">Email notifications</span><span className="block text-xs text-text-secondary">Receive reminder emails before upcoming deadlines</span></div></label></section>
      <section className={sectionClasses}><div className="flex items-center gap-2 mb-5"><CalendarIcon className="w-5 h-5 text-brand"/><h2 className="text-lg font-bold text-text-primary">Connected Accounts</h2></div><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-4 rounded-2xl clay-inset"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-clay-blue/55 rounded-xl flex items-center justify-center shadow-neu-inset"><span className="text-xl" aria-hidden="true">📅</span></div><div><span className="block text-sm font-semibold text-text-primary mb-0.5">Google Calendar</span><span className="block text-xs text-text-secondary">Sync your deadlines to Google Calendar</span></div></div><div className="flex gap-2"><button type="button" onClick={()=>window.open(calendarApi.startSync(),'_self')} className="clay-button px-4 min-h-[40px] rounded-xl bg-clay-blue/45 text-text-primary text-sm font-semibold">Connect</button><button type="button" onClick={handleDisconnectCalendar} className="clay-button px-4 min-h-[40px] rounded-xl pastel-pink text-danger text-sm font-semibold">Disconnect</button></div></div></section>
      <section className={sectionClasses}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-clay-lavender rounded-xl flex items-center justify-center shadow-neu-inset text-brand"><Zap className="w-5 h-5"/></div><div><h2 className="text-sm font-bold text-text-primary mb-0.5">Current Plan</h2><p className="text-xs text-text-secondary">You are currently on the <span className="capitalize font-semibold text-text-primary">{profile?.plan||'free'}</span> tier</p></div></div><span className="px-4 py-2 pastel-lavender text-brand text-sm font-bold uppercase rounded-xl shadow-neu">{profile?.plan==='free'?'Free':'Pro'}</span></div></section>
      <div className="pt-4"><button type="button" onClick={handleSave} disabled={saving} className="w-full sm:w-auto px-8 min-h-[48px] bg-brand text-white rounded-2xl shadow-neu hover:shadow-neu-hover hover:-translate-y-0.5 transition-all disabled:opacity-50 font-bold">{saving?'Saving Changes...':'Save Settings'}</button></div>
    </div>
  </div>;
}
